format_version: 10
pipelines:
  build-swipejobs-customer-preprod-android:
    group: REACT-SWIPEJOBS-PREPROD-APPS
    label_template: "#{APP_BRANCH}-${COUNT}"
    lock_behavior: unlockWhenFinished
    roles:
      - mobile-dev
    environment_variables:
      ANDROID_KEYSTORE_PATH: "../../../frontend-environment-configurations/sj/#{COUNTRY}/release.keystore"
      ANDROID_SDK_ROOT: "/var/go/android-sdk"
    parameters:
      APP_BRANCH: customer-app-5.5.0-RP9909_SJ
      RESOURCES_BRANCH: customer-app-5.5.0-RP9909_SJ
      CONFIG_BRANCH: customer-app-5.5.0-RP9909_SJ
      ENV_CONFIG_PATH: "../frontend-environment-configurations/sj"
      PARTNER_RESOURCES_PATH: "../frontend-partner-resources/sj"
      BUILD_OFFSET: 1182
      BUNDLE_ID: exchange.ondemand.swipejobs.customer.dev1
      APK_PATH: "./android/app/build/outputs/apk/release/"
      NATIVE_PLATFORM: android
      APP_REPO: "git@github.com:swipejobs/frontend-react-native-customer-app.git"
      APP_TYPE: customer
      APPLICATION_NAME: uapp
      ENV: preprod
      OVERRIDE_ENV: preprod
      BARE: true
      COUNTRY: ""
      RUN_TESTS: 1
    materials:
      code:
        git: "#{APP_REPO}"
        auto_update: true
        branch: "#{APP_BRANCH}"
        destination: app_source
      partner_resources:
        git: git@github.com:swipejobs/frontend-partner-resources.git
        auto_update: true
        branch: "#{RESOURCES_BRANCH}"
        destination: "frontend-partner-resources"
      environment_configurations:
        git: git@github.com:swipejobs/frontend-environment-configurations.git
        auto_update: true
        branch: "#{CONFIG_BRANCH}"
        destination: "frontend-environment-configurations"
{% include 'templates/build-partner-native-app-android-all-dev.tmpl' %}
