format_version: 10
pipelines:
  build-swipejobs-customer-preprod-ios:
    group: REACT-SWIPEJOBS-PREPROD-APPS
    label_template: "#{APP_BRANCH}-${COUNT}"
    roles:
      - mobile-dev
    parameters:
      APP_BRANCH: customer-app-5.5.0-RP9909_SJ
      RESOURCES_BRANCH: customer-app-5.5.0-RP9909_SJ
      CONFIG_BRANCH: customer-app-5.5.0-RP9909_SJ
      ENV_CONFIG_PATH: "../frontend-environment-configurations/sj"
      PARTNER_RESOURCES_PATH: "../frontend-partner-resources/sj"
      BUNDLE_ID: exchange.ondemand.swipejobs.customer.dev1
      IPA_PATH: ios/customer.ipa
      USE_TESTFLIGHT: true
      NATIVE_PLATFORM: ios
      APP_REPO: "git@github.com:swipejobs/frontend-react-native-customer-app.git"
      APP_TYPE: customer
      APPLICATION_NAME: uapp
      ENV: preprod
      OVERRIDE_ENV: preprod
      BARE: true
      COUNTRY: ""
      IOS_ACCOUNT_KEY_ID: "BJ68MY8XPJ"
      IOS_ACCOUNT_ISSUER_ID: "69a6de81-29fb-47e3-e053-5b8c7c11a4d1"
      IOS_ACCOUNT_KEY_FILEPATH: "/Users/devops/AuthKey_BJ68MY8XPJ_swipejobs.p8"
      MATCH_GIT_BRANCH: "master"
      RUN_TESTS: 1
    materials:
      code:
        git: "#{APP_REPO}"
        auto_update: true
        branch: "#{APP_BRANCH}"
        destination: app_source
      partner_resources:
        git: git@github.com:swipejobs/frontend-partner-resources.git
        auto_update: true
        branch: "#{RESOURCES_BRANCH}"
        destination: "frontend-partner-resources"
      environment_configurations:
        git: git@github.com:swipejobs/frontend-environment-configurations.git
        auto_update: true
        branch: "#{CONFIG_BRANCH}"
        destination: "frontend-environment-configurations"
{% include 'templates/build-partner-native-app-ios-all-dev.tmpl' %}
